### ISSUE TITLE
Several inconsistencies

### ISSUE THREAD

**Issue by kkrolczyk** [vinland-technology/flict#336]
# Description

Somewhat inconsistent handling of some commands

## Steps for reproduction

```
$ flict verify -il isc -ol mit
{"type": "license", "name": "isc", "license_aliased": "isc", "check": "inbounds_outbound", "outbound": {"type": "license", "name": "mit"}, "outbound_aliased": "MIT", "allowed": true, "problems": [], "compatibility": "Unknown"}
$ flict verify -il mit -ol isc
ERROR:flict:Compatibility between "isc" and "MIT" could not be determined, since "isc" is an unknown license
$ flict list | grep -q ISC && echo "ISC in supported licences"
ISC in supported licences

$ flict display-compatibility MIT ISC # or ISC MIT
{"compatibilities": [{"license": "ISC", "licenses": [{"license": "MIT", "compatible_right": "true", "compatible_left": "true"}, {"license": "ISC", "compatible_right": "true", "compatible_left": "true"}]}, {"license": "MIT", "licenses": [{"license": "MIT", "compatible_right": "true", "compatible_left": "true"}, {"license": "ISC", "compatible_right": "true", "compatible_left": "true"}]}]}

# Sidenote
$ flict display-compatibility BSD-3-Clause and MIT
ERROR:flict:Compatibility between "and" and "MIT" could not be determined, since "and" is an unknown license
# which makes sense, however other commands parse license_expressions in this format
$ flict display-compatibility -h | grep -q license_expression && echo "Command claims support of lic_expr"
Command claims support of lic_expr

$ flict outbound-candidate Apache-2.0 AND LGPL-2.1-only
[]
$ flict outbound-candidate Apache-2.0 MIT  # notice missing AND here
ERROR:flict:Invalid license expression: ['Apache-2.0', 'MIT']. Original cause: (<ReturnCodes.RET_INVALID_EXPRESSSION: (11, 'Invalid expression')>, 'Compatibility between "Apache-2.0 MIT" and "Apache-2.0 MIT" could not be determined, since "Apache-2.0 MIT" is an unknown license')
# firstly, if expression was properly parsed to two components, Apache-2.0 and to MIT, compatibility should be possible to determine, instead licenses seem to be glued back together.
# so i guess, ultimately maybe parsing of license_expr could be somehow unified, or they shouldn't both be named "license_expression"


$ flict -o europe-report.json verify -f example-data/europe.json
Traceback (most recent call last):
  File "/projects/flict/.venv/bin/flict", line 8, in <module>
    sys.exit(main())
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/__main__.py", line 289, in main
    args.func(args)
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/__main__.py", line 248, in verify
    ret = FlictImpl(args).verify()
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/impl.py", line 105, in verify
    return self._handle_lico_project(project_reader, self._args.verify_flict, formatter)
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/impl.py", line 69, in _handle_lico_project
    verification = self.arbiter.verify(project)
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/flictlib/arbiter.py", line 150, in verify
    dep_infos = [self._package_info(dep, licenses) for dep in package.get('dependencies', [])]
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/flictlib/arbiter.py", line 150, in <listcomp>
    dep_infos = [self._package_info(dep, licenses) for dep in package.get('dependencies', [])]
  File "/projects/flict/.venv/lib/python3.10/site-packages/flict/flictlib/arbiter.py", line 118, in _package_info
    'version': package['version'],
KeyError: 'version'
```
## Expected behavior

- I'd expect proper definition of terms ;) use-cases and overall consistency

- I'd expect that commands from `README.md` are added to tests,
and `example-data/europe.json` is updated with missing `package` section
(or the example in `README.md` should be updated accordingly)

- `arbiter.py` should also gracefully handle incorrect input

## Actual behavior

see reproduction steps

## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | 1.2.0 | `flict --version`   |
 | python3 | 3.10.12 | `python3 --version` |
 | os      | Linux | n.a.                |

**Comment by hesa** [comment]
_Sorry for the wall-of-text below_

I will discuss the issues one by one (starting from top) until we have a way forward for each of them:

> $ flict verify -il isc -ol mit
> {"type": "license", "name": "isc", "license_aliased": "isc", "check": "inbounds_outbound", "outbound": {"type": "license", "name": "mit"}, "outbound_aliased": "MIT", "allowed": true, "problems": [], "compatibility": "Unknown"}
> $ flict verify -il mit -ol isc
> ERROR:flict:Compatibility between "isc" and "MIT" could not be determined, since "isc" is an unknown license
> $ flict list | grep -q ISC && echo "ISC in supported licences"
> ISC in supported licences

The above points to (correct me if I am wrong) two problems:
* `isc` vs `ISC` and `mit`vs `MIT`
* Unknown and not unknown (sometimes 0 is returned, sometimes an error)


--------------------



**About isc and ISC | mit ad MT**
* `isc` is not supported, since there is not license called that. 
* `ISC` is supported (https://www.osadl.org/fileadmin/checklists/unreflicenses/ISC.txt)

But looking at `mit` and `MIT` the above makes no sense at all.

I do not dare suggesting checking licenses using `lower()` or similar. 

_**Suggested way forward**_

Remove all alises (e.g. `mit` -> `MIT`) for consistency.
Will look at a way to make use of non-flict data instead of having flict provide alias information for all the licenses.



--------------------





**Unknown and not unknown**

**_Unknown inbound_**

Let's assume we have an inbound license `MIT OR NONESUCH` and we want to check if we can use `GPL-2.0-only` as outbound license. Since `OR` gives the user a choice between two (in this case and also most commonly) licenses I think we need to evaluate the compatibility in two separate "tracks":

1. outbound=`GPL-2.0-only` combined with inbound=`MIT`. This is OK from a compatibility point of view.
2. outbound=`GPL-2.0-only` combined with inbound=`NONESUCH`. This is NOT OK from a compatibility point of view, since `NONESUCH` is an unknown license and therefor the compatibility between the two is unknown.

This leaves us in a situation where we have one compatible way forward (1) and one unknown (2).

From a user point of view I think:
* the preferred answer is that there is a way for you to get compliant, namely (1)
* it would be bad to leave with an error, due to (2)

One can discuss what to do in the case of a single inbound license, e.g. `NONESUCH`, but I'd rather have the compatibility described in the returned data than the error code since we treat all inbounds the same way.

**_Unknown outbound_**

Calculating compatibility between a single **unknown outbound** and inbound licenses will always give an error since we can never know anything about the compatibility. This is reflected in the exit code not being 0.

However, it may be confusing that an unknown sometimes is OK (if inbound is unknown) and sometimes not OK (if outbound is unknown). 

_**Suggested way forward**_

We change the response to always be 0 (if nothing else happens, e.g. bad input data). So, the following:

`$ flict verify -il mit -ol NONESUCH`

should:
* exit with 0

and provide a response saying that:
* compatibility is "No"
* `NONESUCH` is unknown

_Again, sorry for the wall-of-text_

**Comment by hesa** [comment]
OK, next part.

> $ flict display-compatibility MIT ISC # or ISC MIT
> {"compatibilities": [{"license": "ISC", "licenses": [{"license": "MIT", "compatible_right": "true", "compatible_left": "true"}, {"license": "ISC", "compatible_right": "true", "compatible_left": "true"}]}, {"license": "MIT", "licenses": [{"license": "MIT", "compatible_right": "true", "compatible_left": "true"}, {"license": "ISC", "compatible_right": "true", "compatible_left": "true"}]}]}

I assume this is an addition to the discussion about MIT/mit and ISC/isc above. If not, can you explain the problem?
 
> \# Sidenote
> $ flict display-compatibility BSD-3-Clause and MIT
> ERROR:flict:Compatibility between "and" and "MIT" could not be determined, since "and" is an unknown license
> \# which makes sense, 

:+1: 

> however other commands parse license_expressions in this format
> $ flict display-compatibility -h | grep -q license_expression && echo "Command claims support of lic_expr"
> Command claims support of lic_expr

:+1: 

**_Suggested way forward_**

Will update doc (README, help...) to reflect that 
* a list of licenses, including `WITH`  (e.g. GPL-​2.0-​only WITH Classpath-​excep­tion-​2.0`) is supported
* but expressions, i.e. using `(`, `)`, `AND`, `OR` are NOT supported

**Comment by kkrolczyk** [comment]
Hi @hesa,

first of all, thanks for the rich answers, please don't worry about the wall of text - IMHO better to be verbose but clear, than succinct and misunderstood. To address your remarks:  

1. while indeed - the small caps isc and capital ISC could resolve to same name (I also cannot say, would this be always beneficial or not) - this is only one side of the coin. Here, I was thinking more in direction of confusing messages, to a user; if inbound isc/ISC is unknown, should it even be processed, given that the resulting state will be "Unknown" / "allowed: True"? Perhaps in some cases this could be even misleading. It would seem somewhat logical - i think - that same would apply to reversed order, as it also would be "unknown and allowed", in case we didn't know the inbound, and what restrictions could it impose?

This to some degree, in my understanding, connects with the second topic/section. If it was decided that we would not even parse unknown license, how come there are no obstacles to determine compatibility, for "display-compatibility"? 

2. second item concerns usage of the term `license_expression`. It would seem (please correct me if i am wrong), that such term would have the same meaning, regardless where it is used. So (...as a user...) I would then expect to handle same "syntax", even if in particular place it makes little sense. 
Otherwise, if this should not be the case, like for example "and" in `flict display-compatibility BSD-3-Clause and MIT` - I think it might justify naming those arguments differently. License expression would mean N licenses, always combined with conjunctions, and N licenses without any - would be named (for example) list of licenses? 
Same thing applies to next section, `outbound-candidate`. I think, a secondary goal of the flict tool - might be to promote deeper understanding of compliance / license topics - thus, it could in a way "educate", what are certain things, and why they make sense in certain expressions/context, and not in others.

**Comment by hesa** [comment]
## Your comment (1)

> if inbound isc/ISC is unknown, should it even be processed, given that the resulting state will be "Unknown" / "allowed: True"?

I think so. The expression "Unknown OR allowed" is something flict can inform the user she/he can be compliant in a simple way. Without first having to take the following time consuming steps to avoid getting an error from flict:
* get an SPDX ID for the unknown license (not saying they're slow, but not as fast as flict can return an answer)
* get the unknown license in to OSADL's matrix (not saying they're slow, but not as fast as flict can return an answer)

So, I think flict should process and not return an error if an unknown license is found. For the user's sake.

Do you think that a call `verify` with no way to be compliant was found should return an error?

_Note: A single unknown inbound license can never return `"allowed": true`_


## Your comment (2)

Let's use "list of licenses" and "license expression" as two separate texts in the documentation.

**Comment by hesa** [comment]
Closed by:
#343 
#340 
#338
